version: '2'
services:
  qcweb:
    networks:
      default:
        ipv4_address: 172.18.0.20
    image: "huzhihui/qcweb:1.0.0"
    container_name: qcweb
    volumes:
      - "/alidata/docker/qcweb:/alidata/docker/qcweb"
      - "/alidata/docker/qcweb/config.json:/usr/local/server/app/config.json"
      - "/alidata/docker/qcweb/logs:/usr/local/logs"
      - "/alidata/view:/alidata/view"
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: huzhihui
